pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "BancoAndino"

include ':app'
include ':02_JetpackCompose:app'

project(':02_JetpackCompose:app').projectDir =
        file('02_JetpackCompose/app')